/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.doancuoiky.ui;

import com.doancuoiky.core.FileUtils;
import java.awt.Component;
import java.awt.Font;
import java.awt.Image;
import java.net.URL;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.RowFilter;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;
import javax.swing.table.TableRowSorter;
import com.doancuoiky.ui.TaoSpMoiFrame;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import com.doancuoiky.ui.ChinhSuaSpFrame;
import java.awt.Color;
import java.text.NumberFormat;
import java.util.Locale;
import com.doancuoiky.dao.ProductDao;
import com.doancuoiky.core.FileUtils;
import java.text.DecimalFormat;
import java.util.EventObject;
import javax.swing.DefaultCellEditor;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JFrame;
import javax.swing.SwingUtilities;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableColumn;

/**
 *
 * @author phuongmd
 */
public class BanHangPanel extends javax.swing.JPanel {


    public BanHangPanel() {
        initComponents();
        setUptableView();
        setUptableViewTinhTien();
        setupEditSp();
        remove_focus_table();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tfSearch = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableSpDangBan = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TableTinhTien = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        tfInputMaKH = new javax.swing.JTextField();
        btnsearchMakH = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tfInputvoucher = new javax.swing.JTextField();
        btnapplyvoucher = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(1400, 900));

        jPanel2.setPreferredSize(new java.awt.Dimension(1400, 900));

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel1.setText("Tính tiền");

        tfSearch.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        btnSearch.setText("Tìm kiếm");
        btnSearch.setAlignmentY(0.0F);
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1400, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 112, Short.MAX_VALUE)
        );

        jScrollPane1.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N

        TableSpDangBan.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        TableSpDangBan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã Sản Phẩm", "Ảnh Sản Phẩm ", "Tên Sản Phẩm", "Số Lượng", "Giá Bán", "Barcode"
            }
        ));
        jScrollPane1.setViewportView(TableSpDangBan);

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel2.setText("Danh sách sản phẩm đang bán");

        jScrollPane2.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N

        TableTinhTien.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        TableTinhTien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã Sản Phẩm", "Tên Sản Phẩm", "Số Lượng", "Đơn giá", "Thành tiền"
            }
        ));
        jScrollPane2.setViewportView(TableTinhTien);

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.darkGray, java.awt.Color.darkGray, java.awt.Color.darkGray, java.awt.Color.darkGray));
        jPanel1.setPreferredSize(new java.awt.Dimension(358, 800));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel3.setText("MÃ KHÁCH HÀNG");

        btnsearchMakH.setText("Tìm kiếm");

        jLabel4.setText("Tên Khách Hàng");

        jTextField1.setDisabledTextColor(new java.awt.Color(242, 242, 242));
        jTextField1.setEnabled(false);

        jLabel5.setText("SĐT");

        jTextField2.setDisabledTextColor(new java.awt.Color(242, 242, 242));
        jTextField2.setEnabled(false);

        jLabel6.setText("Tổng điểm tích lũy:");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 0, 0));
        jLabel7.setText("456456");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel8.setText("KHUYẾN MÃI");

        btnapplyvoucher.setText("Áp dụng");

        jButton1.setBackground(new java.awt.Color(0, 102, 102));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Thanh toán");
        jButton1.setToolTipText("");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(255, 0, 0));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Hủy thanh toán");
        jButton2.setPreferredSize(new java.awt.Dimension(160, 23));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel8)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(tfInputvoucher, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 233, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jTextField2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfInputMaKH, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnsearchMakH)
                            .addComponent(btnapplyvoucher)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfInputMaKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnsearchMakH))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfInputvoucher, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnapplyvoucher))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1001, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1006, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(395, 395, 395)
                        .addComponent(tfSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(102, 102, 102)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(184, 184, 184))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(tfSearch)
                            .addComponent(btnSearch))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 850, Short.MAX_VALUE)
                        .addContainerGap())))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        search_sp(tfSearch.getText());
    }//GEN-LAST:event_btnSearchActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void reset_filter(){
        TableRowSorter<DefaultTableModel> rowSorter;
        DefaultTableModel model = (DefaultTableModel) TableSpDangBan.getModel();
        rowSorter = new TableRowSorter<>(model);
        TableSpDangBan.setRowSorter(rowSorter);
        rowSorter.setRowFilter(RowFilter.regexFilter("(?i)"));
    }
    
    private void search_sp (String str) {
        TableRowSorter<DefaultTableModel> rowSorter;
        DefaultTableModel model = (DefaultTableModel) TableSpDangBan.getModel();
        rowSorter = new TableRowSorter<>(model);
        TableSpDangBan.setRowSorter(rowSorter);
        rowSorter.setRowFilter(RowFilter.regexFilter("(?i)" + str));
    }
    
    public void reloadtableView(){
        DefaultTableModel model = (DefaultTableModel) TableSpDangBan.getModel();
        model.setRowCount(0);
        tfSearch.setText("");
        reset_filter();
        setUptableView(); 
    }
    
    private void setUptableView(){
        TableSpDangBan.setRowHeight(50); 
        TableSpDangBan.setShowHorizontalLines(true);
        TableSpDangBan.setShowVerticalLines(false);
        TableSpDangBan.setGridColor(Color.LIGHT_GRAY);
        TableSpDangBan.setDefaultEditor(Object.class, null);
        TableSpDangBan.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 16));
        DefaultTableModel model = (DefaultTableModel) TableSpDangBan.getModel();
        Object[][] data = ProductDao.getAllProductBanHang();

        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(SwingConstants.CENTER);
        // Thêm từng dòng dữ liệu vào bảng
        for (Object[] row : data) {
            model.addRow(row);
        }
        //căn giữa cho header
        JTableHeader header = TableSpDangBan.getTableHeader();
        for (int i = 0; i < TableSpDangBan.getColumnCount(); i++) {
            TableColumn column = TableSpDangBan.getColumnModel().getColumn(i);
            column.setHeaderRenderer(centerRenderer);
        }
        //căn giữa cho row
        for (int i = 0; i < TableSpDangBan.getColumnCount(); i++) {
            if (i != 1 && i!= 4) {
                TableSpDangBan.getColumnModel().getColumn(i).setCellRenderer(centerRenderer);
            }
        }  
        TableSpDangBan.getColumnModel().getColumn(1).setCellRenderer(new ImageCellRenderer());
        FileUtils.applyRedTextOnSelect(TableSpDangBan, new int[]{1}, new int[]{4});
    }
    
        private void setUptableViewTinhTien(){
            TableTinhTien.setRowHeight(65); 
            TableTinhTien.setShowHorizontalLines(true);
            TableTinhTien.setShowVerticalLines(false);
            TableTinhTien.setGridColor(Color.LIGHT_GRAY);
            TableTinhTien.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 16));
            DefaultTableModel model = new DefaultTableModel(null, new Object[]{"Mã Sản Phẩm", "Tên Sản Phẩm", "Số Lượng", "Đơn Giá", "Thành Tiền", ""}) {
                @Override
                public boolean isCellEditable(int row, int column) {
                    return column == 2 || column == 5; // cho phép chỉnh sửa cột
                }
            };
            TableTinhTien.setModel(model);
            DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
            centerRenderer.setHorizontalAlignment(SwingConstants.CENTER);
            //căn giữa cho header
            JTableHeader header = TableTinhTien.getTableHeader();
            for (int i = 0; i < TableTinhTien.getColumnCount(); i++) {
                TableColumn column = TableTinhTien.getColumnModel().getColumn(i);
                column.setHeaderRenderer(centerRenderer);
            }
        model.addTableModelListener(e -> {
        int row = e.getFirstRow();
        int col = e.getColumn();
        if (col == 2) { // cột số lượng thay đổi
            try {
                int soLuong = Integer.parseInt(model.getValueAt(row, 2).toString());
                int giaBan = Integer.parseInt(model.getValueAt(row, 3).toString().replace(" VND", "").trim());
                int thanhTien = soLuong * giaBan;
                model.setValueAt(thanhTien, row, 4); // cập nhật lại thành tiền
            } catch (Exception ex) {
                // Nếu lỗi định dạng, không cập nhật
                System.err.println("Lỗi khi tính thành tiền: " + ex.getMessage());
            }
        }
    });
    }
        
     private void remove_focus_table(){
        jPanel2.addMouseListener(new MouseAdapter() {
       @Override
       public void mousePressed(MouseEvent e) {
           TableTinhTien.clearSelection(); // bỏ chọn dòng
           TableTinhTien.requestFocusInWindow(); // chuyển focus đi
           TableSpDangBan.clearSelection(); 
           TableSpDangBan.requestFocusInWindow(); 
       }
        });
     }  
       
     
    private void add_sp_to_tableviewTinhTien(Object[] data) {
        DefaultTableModel model = (DefaultTableModel) TableTinhTien.getModel();
        model.addRow(data);
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(SwingConstants.CENTER);
         //căn giữa text
        for (int i = 0; i < TableTinhTien.getColumnCount(); i++) {
            if (i != 3 && i!= 4) {
                TableTinhTien.getColumnModel().getColumn(i).setCellRenderer(centerRenderer);
            }
        }  
        FileUtils.applyRedTextOnSelect(TableTinhTien, new int[]{}, new int[]{3, 4});
        TableColumn actionCol = TableTinhTien.getColumnModel().getColumn(5);
        actionCol.setCellRenderer(new ButtonRenderer());
        actionCol.setCellEditor(new ButtonEditor(TableTinhTien));
        actionCol.setMaxWidth(60);
    }
    
    private void setupEditSp(){
        TableSpDangBan.addMouseListener(new MouseAdapter() {
        @Override
        public void mouseClicked(MouseEvent e) {
            if (e.getClickCount() == 2 && TableSpDangBan.getSelectedRow() != -1) {
                int row = TableSpDangBan.getSelectedRow();  // dòng được chọn
                int colCount = TableSpDangBan.getColumnCount();
                String maSp = TableSpDangBan.getValueAt(row, 0).toString();
                String tenSp = TableSpDangBan.getValueAt(row, 2).toString();
                String SoLuong = TableSpDangBan.getValueAt(row, 4).toString();
                String GiaBan = TableSpDangBan.getValueAt(row, 4).toString();
                add_sp_to_tableviewTinhTien(new Object[]{maSp, tenSp, 1, GiaBan, GiaBan});
            }
        }
    });
    }
 
    class ImageCellRenderer extends JLabel implements TableCellRenderer {
        public ImageCellRenderer() {
            setHorizontalAlignment(SwingConstants.CENTER); // Căn giữa ngang
            setVerticalAlignment(SwingConstants.CENTER);   // Căn giữa dọc
        }

        @Override
        public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
            ImageIcon icon_base64 = FileUtils.convert_base64_to_image((String) value, 60, 60);
            setIcon(icon_base64);
            setText(null); // Không hiển thị text
            return this;
        }
    }
    
    public class ButtonRenderer extends JButton implements TableCellRenderer {

       public ButtonRenderer() {
           setOpaque(true);
           setForeground(Color.RED);
           setText("X");
           setFocusPainted(false);
           setBorderPainted(false);
           setContentAreaFilled(false);
       }

       @Override
       public Component getTableCellRendererComponent(JTable table, Object value,
                                                      boolean isSelected, boolean hasFocus,
                                                      int row, int column) {
           return this;
       }
   }
    
    public class ButtonEditor extends DefaultCellEditor {
        private JButton button;
        private JTable table;

        public ButtonEditor(JTable table) {
            super(new JCheckBox());
            this.table = table;

            button = new JButton("X");
            button.setForeground(Color.RED);
            button.setFocusPainted(false);
            button.setBorderPainted(false);
            button.setContentAreaFilled(false);

            button.addActionListener(e -> {
                int row = table.getEditingRow();
                if (row != -1) {
                    ((DefaultTableModel) table.getModel()).removeRow(row);
                }
            });
        }

        @Override
        public Component getTableCellEditorComponent(JTable table, Object value,
                                                     boolean isSelected, int row, int column) {
            return button;
        }

        @Override
        public Object getCellEditorValue() {
            return "X";
        }

        @Override
        public boolean isCellEditable(EventObject e) {
            return true;
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TableSpDangBan;
    private javax.swing.JTable TableTinhTien;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnapplyvoucher;
    private javax.swing.JButton btnsearchMakH;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField tfInputMaKH;
    private javax.swing.JTextField tfInputvoucher;
    private javax.swing.JTextField tfSearch;
    // End of variables declaration//GEN-END:variables
}
