/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.doancuoiky.ui;

import java.awt.Cursor;
import java.awt.Image;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
import com.doancuoiky.core.FileUtils;
import com.doancuoiky.model.ProductModel;
import com.doancuoiky.dao.ProductDao;
import java.net.URL;
import javax.swing.JOptionPane;


/**
 *
 * @author phuongmd
 */
public class ChinhSuaSpFrame extends javax.swing.JFrame {

    private String image_upload_base64; 
    private ProductModel ProductData;
    private static SanPhamPanel parentFrame;
    /**
     * Creates new form TaoSpMoiFrame
     */
    public ChinhSuaSpFrame(SanPhamPanel parent, String Masp, String imageSp, String TenSp, String SoLuong, String GiaBan, String LoaiHang, String BarCode, String TrangThai) {
        parentFrame = parent;
        initComponents();
        setup_click_add_image();
        add_data_field_edit(Masp, imageSp, TenSp, SoLuong, GiaBan, LoaiHang, BarCode, TrangThai);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tfMaSP = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tfTenSP = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tfSoLuong = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tfGiaBan = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tfBarcode = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        dlTrangThai = new javax.swing.JComboBox<>();
        dlLoaiHang = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        lbImage = new javax.swing.JLabel();
        btnCreateSP = new javax.swing.JButton();
        btnCreateSP1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Chỉnh sửa sản phẩm");

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 0));
        jLabel1.setText("Tạo Sản Phẩm ");
        jLabel1.setToolTipText("");

        jLabel2.setText("Mã sản phẩm*");

        jLabel3.setText("Tên sản phẩm");

        jLabel4.setText("Số lượng");

        jLabel5.setText("Giá bán");

        tfGiaBan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfGiaBanActionPerformed(evt);
            }
        });

        jLabel6.setText("Loại hàng");

        jLabel7.setText("BarCode");

        jLabel8.setText("Trạng thái");

        dlTrangThai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Đang kinh doanh", "Ngừng kinh doanh" }));
        dlTrangThai.setPreferredSize(new java.awt.Dimension(64, 23));
        dlTrangThai.setSize(new java.awt.Dimension(64, 23));

        dlLoaiHang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Quần áo", "Áo khoác", "Túi xách", "Giày" }));
        dlLoaiHang.setPreferredSize(new java.awt.Dimension(64, 23));
        dlLoaiHang.setSize(new java.awt.Dimension(64, 23));

        jLabel9.setText("Hình ảnh sản phẩm");

        lbImage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbImage.setText("Thêm ảnh");
        lbImage.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lbImage.setPreferredSize(new java.awt.Dimension(250, 250));

        btnCreateSP.setFont(new java.awt.Font("Helvetica Neue", 1, 16)); // NOI18N
        btnCreateSP.setText("Xoá sản phẩm");
        btnCreateSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateSPActionPerformed(evt);
            }
        });

        btnCreateSP1.setFont(new java.awt.Font("Helvetica Neue", 1, 16)); // NOI18N
        btnCreateSP1.setText("Cập nhật");
        btnCreateSP1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateSP1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfGiaBan)
                    .addComponent(tfBarcode)
                    .addComponent(dlLoaiHang, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tfTenSP)
                    .addComponent(tfSoLuong)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfMaSP, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(209, 209, 209)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel8)
                        .addComponent(jLabel9)
                        .addComponent(dlTrangThai, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbImage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnCreateSP)
                        .addGap(18, 18, 18)
                        .addComponent(btnCreateSP1)))
                .addGap(44, 44, 44))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfMaSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dlTrangThai, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(tfTenSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tfSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tfGiaBan, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(dlLoaiHang, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel7))
                    .addComponent(lbImage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addComponent(tfBarcode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCreateSP, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCreateSP1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfGiaBanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfGiaBanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfGiaBanActionPerformed

    private void btnCreateSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateSPActionPerformed
        if (!tfMaSP.getText().isEmpty()) {
            get_data_field_and_add_model();
//            ProductDao.createProduct(ProductData)
            if (true){
                JOptionPane.showMessageDialog(null, "Đã thêm sản phẩm thành công");
                this.dispose();
                parentFrame.reloadtableView();
            }else {
                JOptionPane.showMessageDialog(null, "Mã sản phẩm bị trùng lập vui lòng kiểm tra lại");
            }
        }else {
            JOptionPane.showMessageDialog(null, "Vui lòng nhập thông tin mã sản phẩm");
        }

    }//GEN-LAST:event_btnCreateSPActionPerformed

    private void btnCreateSP1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateSP1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCreateSP1ActionPerformed

    private void add_data_field_edit(String Masp, String imageSp, String TenSp, String SoLuong, String GiaBan, String LoaiHang, String BarCode, String TrangThai) {
        tfMaSP.setText(Masp);
        tfTenSP.setText(TenSp);
        tfSoLuong.setText(SoLuong);
        tfGiaBan.setText(GiaBan);
        dlLoaiHang.setSelectedItem(LoaiHang);
        tfBarcode.setText(BarCode);
        dlTrangThai.setSelectedItem(TrangThai);
//        ImageIcon icon_base64 = FileUtils.convert_base64_to_image(imageSp, 250, 250);
//        lbImage.setIcon(icon_base64);
//        lbImage.setText("");
        System.out.print(imageSp);
        URL imageUrl = getClass().getResource((String) imageSp);
        ImageIcon icon = new ImageIcon(imageUrl);
        Image scaled = icon.getImage().getScaledInstance(
        lbImage.getWidth(), lbImage.getHeight(), Image.SCALE_SMOOTH);
        lbImage.setIcon(new ImageIcon(scaled));
        lbImage.setText("");  // Xóa chữ cũ
    }
    
    private void get_data_field_and_add_model(){
        String maSp = tfMaSP.getText();
        String tenSp = tfTenSP.getText();
        String soLuongSp = tfSoLuong.getText();
        String giaBanSp = tfGiaBan.getText();
        String loaiHangSp = (String) dlLoaiHang.getSelectedItem();
        String barCodeSp = tfBarcode.getText();
        String trangThaiSp = (String) dlTrangThai.getSelectedItem();
        
        ProductData = new ProductModel(maSp, tenSp, soLuongSp, giaBanSp, loaiHangSp, barCodeSp, trangThaiSp, image_upload_base64);
    }
    
    private void chose_upload_image () {
        JFileChooser fileChooser = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter(
                "Image files", "jpg", "jpeg", "png", "gif");
        fileChooser.setFileFilter(filter);

        int result = fileChooser.showOpenDialog(null);
        if (result == JFileChooser.APPROVE_OPTION) {
            File selectedFile = fileChooser.getSelectedFile();
            ImageIcon icon = new ImageIcon(selectedFile.getAbsolutePath());
            image_upload_base64 = selectedFile.getAbsolutePath();
            // Resize ảnh cho vừa JLabel
            Image scaled = icon.getImage().getScaledInstance(
                    lbImage.getWidth(), lbImage.getHeight(), Image.SCALE_SMOOTH);
            lbImage.setIcon(new ImageIcon(scaled));
            lbImage.setText("");  // Xóa chữ cũ
            // Chuyển sang Base64 và lưu lại
            image_upload_base64 = FileUtils.convert_image_to_base64(selectedFile);
        }
    }
    
    private void setup_click_add_image() {
        lbImage.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR)); // Đổi con trỏ cho dễ nhìn
        lbImage.addMouseListener(new MouseAdapter() {
        @Override
        public void mouseClicked(MouseEvent e) {
            chose_upload_image();
        }
    });
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreateSP;
    private javax.swing.JButton btnCreateSP1;
    private javax.swing.JComboBox<String> dlLoaiHang;
    private javax.swing.JComboBox<String> dlTrangThai;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbImage;
    private javax.swing.JTextField tfBarcode;
    private javax.swing.JTextField tfGiaBan;
    private javax.swing.JTextField tfMaSP;
    private javax.swing.JTextField tfSoLuong;
    private javax.swing.JTextField tfTenSP;
    // End of variables declaration//GEN-END:variables
}
