/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.doancuoiky.ui;
//import com.doancuoiky.model.LoginModel;
import com.doancuoiky.core.Uicore;
import com.doancuoiky.ui.BanHangPanel;
import com.doancuoiky.ui.SanPhamPanel;
import com.doancuoiky.ui.QuanLyKHPanel;
import com.doancuoiky.ui.VoucherPanel;
import com.doancuoiky.ui.QuanLyNVPanel;
import com.doancuoiky.ui.ThongKePanel;
import com.doancuoiky.ui.LoginFrame;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.event.FocusEvent;
import java.awt.event.FocusListener;
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.net.URL;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;




/**
 *
 * @author ADMIN
 */
public class MemberFrame extends javax.swing.JFrame {
    private BanHangPanel banhangPanel;
    private SanPhamPanel sanphamPanel;
    private QuanLyKHPanel quanlyKHPanel;
    private VoucherPanel quanlyVoucherPanel;
    private ThongKePanel thongKePanel;
    private String currentPanelName = "MainFrame";
    private String HoTen;
    private String Role;
    private String Username;
    /**
     * Creates new form AdminFrame
     */
    public MemberFrame(String HoTen, String Role, String Username) {
        this.HoTen = HoTen;
        this.Role = Role;
        this.Username = Username;
        initComponents();
        mainContentPanel.setLayout(new CardLayout());
        initMenu();
        setupIcon();
        setupUI();
        FocusableButtonmenu(btnBanHang);
        switchToPanel("banhangPanel", false);
        Uicore.applyBlackBorderToAllTextFields(this);
        setResizable(false);  

    }       
    
    private void initMenu() {
    // Khởi tạo Ban hàng
    this.banhangPanel = new BanHangPanel();
    mainContentPanel.add(banhangPanel, "banhangPanel");

    this.sanphamPanel = new SanPhamPanel();
    mainContentPanel.add(sanphamPanel, "sanphamPanel");
    
    this.quanlyKHPanel = new QuanLyKHPanel();
    mainContentPanel.add(quanlyKHPanel, "quanlyKHPanel");
    
    this.quanlyVoucherPanel = new VoucherPanel();
    mainContentPanel.add(quanlyVoucherPanel, "quanlyVoucherPanel");
    
    QuanLyNVPanel quanlyNVPanel = new QuanLyNVPanel();
    mainContentPanel.add(quanlyNVPanel, "quanlyNVPanel");
    
    this.thongKePanel = new ThongKePanel();
    mainContentPanel.add(thongKePanel, "thongKePanel");
    }
    
    private void setupUI(){
        name.setText(HoTen);
        position.setText(Role);
    }
    
    private void setupIcon(){
       setupIconJabel(Avatar, "/image/ic_menu/ic_header.png");
       setupIconButton(btnBanHang, "/image/ic_menu/ic_banHang.png");
       setupIconButton(btnQlSanPham, "/image/ic_menu/ic_sanPham.png");
       setupIconButton(btnKhachHang, "/image/ic_menu/ic_khachHang.png");
       setupIconButton(btnThongKe, "/image/ic_menu/ic_thongKe.png");
       setupIconButton(BtnDangXuat, "/image/ic_menu/ic_dangXuat.png");                
    }
    
    private void setupIconButton(JButton jbutton, String url){
        try {
            // Load ảnh từ resources
            URL iconURL = getClass().getResource(url);
            if (iconURL == null) {
                throw new IOException("Không tìm thấy ảnh trong resource");
            }

            BufferedImage originalImage = ImageIO.read(iconURL);

            BufferedImage resized = resizeImage(originalImage, 25, 30);

            jbutton.setIcon(new ImageIcon(resized));

        } catch (IOException e) {
            e.printStackTrace();
        }
    }
    
    private void setupIconJabel(JLabel jlabel, String url){
        try {
            // Load ảnh từ resources
            URL iconURL = getClass().getResource(url);
            if (iconURL == null) {
                throw new IOException("Không tìm thấy ảnh trong resource");
            }

            BufferedImage originalImage = ImageIO.read(iconURL);

            BufferedImage resized = resizeImage(originalImage, 160, 160);

            jlabel.setIcon(new ImageIcon(resized));

        } catch (IOException e) {
            e.printStackTrace();
        }
    }
    
    private BufferedImage resizeImage(BufferedImage img, int width, int height) {
        Image tmp = img.getScaledInstance(width, height, Image.SCALE_SMOOTH);
        BufferedImage resized = new BufferedImage(width, height, BufferedImage.TYPE_INT_ARGB);
        Graphics2D g2d = resized.createGraphics();
        g2d.drawImage(tmp, 0, 0, null);
        g2d.dispose();
        return resized;
    }

    /**
     * This method is cAalled from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        BorderLayout = new javax.swing.JPanel();
        menuPanel = new javax.swing.JPanel();
        jPanelInfo = new javax.swing.JPanel();
        name = new javax.swing.JLabel();
        position = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Avatar = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        JpanelMenu = new javax.swing.JPanel();
        btnQlSanPham = new javax.swing.JButton();
        btnBanHang = new javax.swing.JButton();
        BtnDangXuat = new javax.swing.JButton();
        btnKhachHang = new javax.swing.JButton();
        btnThongKe = new javax.swing.JButton();
        mainContentPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Quản lý bán hàng");

        menuPanel.setBackground(new java.awt.Color(255, 255, 255));

        jPanelInfo.setBackground(new java.awt.Color(255, 255, 255));
        jPanelInfo.setAlignmentX(0.0F);
        jPanelInfo.setAlignmentY(0.0F);
        jPanelInfo.setPreferredSize(new java.awt.Dimension(200, 100));

        jLabel2.setText("Chức vụ:");

        jLabel1.setText("Nhân viên:");

        Avatar.setPreferredSize(new java.awt.Dimension(160, 160));

        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel3.setText("Quản lý bán hàng");

        javax.swing.GroupLayout jPanelInfoLayout = new javax.swing.GroupLayout(jPanelInfo);
        jPanelInfo.setLayout(jPanelInfoLayout);
        jPanelInfoLayout.setHorizontalGroup(
            jPanelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInfoLayout.createSequentialGroup()
                .addGroup(jPanelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelInfoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelInfoLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(4, 4, 4)
                                .addComponent(name))
                            .addGroup(jPanelInfoLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(position))))
                    .addGroup(jPanelInfoLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(Avatar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelInfoLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel3)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelInfoLayout.setVerticalGroup(
            jPanelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInfoLayout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Avatar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(jPanelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(name))
                .addGap(18, 18, 18)
                .addGroup(jPanelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(position))
                .addGap(15, 15, 15))
        );

        JpanelMenu.setBackground(new java.awt.Color(255, 255, 0));
        JpanelMenu.setAlignmentX(0.0F);
        JpanelMenu.setAlignmentY(0.0F);
        JpanelMenu.setPreferredSize(new java.awt.Dimension(200, 600));

        btnQlSanPham.setBackground(new java.awt.Color(255, 255, 0));
        btnQlSanPham.setText("QL Sản Phẩm");
        btnQlSanPham.setBorderPainted(false);
        btnQlSanPham.setFocusPainted(false);
        btnQlSanPham.setPreferredSize(new java.awt.Dimension(78, 25));
        btnQlSanPham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQlSanPhamActionPerformed(evt);
            }
        });

        btnBanHang.setBackground(new java.awt.Color(255, 255, 0));
        btnBanHang.setText("Bán Hàng");
        btnBanHang.setAlignmentY(0.0F);
        btnBanHang.setBorderPainted(false);
        btnBanHang.setFocusPainted(false);
        btnBanHang.setPreferredSize(new java.awt.Dimension(200, 25));
        btnBanHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBanHangActionPerformed(evt);
            }
        });

        BtnDangXuat.setBackground(new java.awt.Color(255, 255, 0));
        BtnDangXuat.setText("Đăng Xuất");
        BtnDangXuat.setBorderPainted(false);
        BtnDangXuat.setFocusPainted(false);
        BtnDangXuat.setPreferredSize(new java.awt.Dimension(78, 25));
        BtnDangXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnDangXuatActionPerformed(evt);
            }
        });

        btnKhachHang.setBackground(new java.awt.Color(255, 255, 0));
        btnKhachHang.setText("Khách Hàng");
        btnKhachHang.setBorderPainted(false);
        btnKhachHang.setFocusPainted(false);
        btnKhachHang.setPreferredSize(new java.awt.Dimension(78, 25));
        btnKhachHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKhachHangActionPerformed(evt);
            }
        });

        btnThongKe.setBackground(new java.awt.Color(255, 255, 0));
        btnThongKe.setText("Thống Kê");
        btnThongKe.setBorderPainted(false);
        btnThongKe.setFocusPainted(false);
        btnThongKe.setPreferredSize(new java.awt.Dimension(78, 25));
        btnThongKe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThongKeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout JpanelMenuLayout = new javax.swing.GroupLayout(JpanelMenu);
        JpanelMenu.setLayout(JpanelMenuLayout);
        JpanelMenuLayout.setHorizontalGroup(
            JpanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnBanHang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnQlSanPham, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(BtnDangXuat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(JpanelMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(JpanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnKhachHang, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnThongKe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        JpanelMenuLayout.setVerticalGroup(
            JpanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JpanelMenuLayout.createSequentialGroup()
                .addComponent(btnBanHang, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(btnQlSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(btnKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(btnThongKe, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(136, 136, 136)
                .addComponent(BtnDangXuat, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 100, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout menuPanelLayout = new javax.swing.GroupLayout(menuPanel);
        menuPanel.setLayout(menuPanelLayout);
        menuPanelLayout.setHorizontalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelInfo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(JpanelMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        menuPanelLayout.setVerticalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPanelLayout.createSequentialGroup()
                .addComponent(jPanelInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(JpanelMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 606, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        mainContentPanel.setForeground(new java.awt.Color(255, 255, 255));
        mainContentPanel.setPreferredSize(new java.awt.Dimension(1400, 900));
        mainContentPanel.setVerifyInputWhenFocusTarget(false);

        javax.swing.GroupLayout mainContentPanelLayout = new javax.swing.GroupLayout(mainContentPanel);
        mainContentPanel.setLayout(mainContentPanelLayout);
        mainContentPanelLayout.setHorizontalGroup(
            mainContentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1387, Short.MAX_VALUE)
        );
        mainContentPanelLayout.setVerticalGroup(
            mainContentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout BorderLayoutLayout = new javax.swing.GroupLayout(BorderLayout);
        BorderLayout.setLayout(BorderLayoutLayout);
        BorderLayoutLayout.setHorizontalGroup(
            BorderLayoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BorderLayoutLayout.createSequentialGroup()
                .addComponent(menuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mainContentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 1387, Short.MAX_VALUE))
        );
        BorderLayoutLayout.setVerticalGroup(
            BorderLayoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menuPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BorderLayoutLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainContentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 916, Short.MAX_VALUE)
                .addContainerGap())
        );

        mainContentPanel.getAccessibleContext().setAccessibleName("");

        jScrollPane1.setViewportView(BorderLayout);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1593, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 928, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void setupresetbgmenu(JButton button) {
        button.setFocusable(true); 
        button.setFocusPainted(false); 
        button.setContentAreaFilled(false);
        button.setOpaque(true);
        button.setBackground(new java.awt.Color(255, 255, 0));
    }
    
    private void FocusableButtonmenu(JButton button) {
        button.setFocusable(true); 
        button.setFocusPainted(false); 
        button.setContentAreaFilled(false);
        button.setOpaque(true);
        button.setBackground(new java.awt.Color(153, 153 , 153));
    }
    
    
    private void resetbgmenu(){
        setupresetbgmenu(btnBanHang);
        setupresetbgmenu(btnQlSanPham);   
        setupresetbgmenu(BtnDangXuat);
        setupresetbgmenu(btnKhachHang); 
        setupresetbgmenu(btnThongKe);
    }
    
    public Boolean switchToPanel(String panelName, Boolean isCheck) {
        if (currentPanelName.equals("banhangPanel") & banhangPanel.isMaHoaDon & isCheck) {
            int result = JOptionPane.showConfirmDialog(
                    this,
                    "Bạn có hoá đơn chưa thanh toán nếu thoát ra sẽ mất hết thông tin đã nhập. Bạn có chắc chắn không?",
                    "Thông báo",
                    JOptionPane.YES_NO_OPTION
            );
            if (result != JOptionPane.YES_OPTION) {
                return false; 
            }
        }
        CardLayout cl = (CardLayout) mainContentPanel.getLayout();
        cl.show(mainContentPanel, panelName);
        currentPanelName = panelName;
        return true;
    }
    
    private void btnBanHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBanHangActionPerformed
        if (switchToPanel("banhangPanel", false)){
            banhangPanel.load_san_pham();
            Boolean a = banhangPanel.isMaHoaDon;
            resetbgmenu();
            FocusableButtonmenu(btnBanHang);
        };
    }//GEN-LAST:event_btnBanHangActionPerformed

    private void btnQlSanPhamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQlSanPhamActionPerformed
        if (switchToPanel("sanphamPanel", true)){
            resetbgmenu();
            sanphamPanel.getUserModel(Username);
            FocusableButtonmenu(btnQlSanPham);
        };
    }//GEN-LAST:event_btnQlSanPhamActionPerformed

    private void BtnDangXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnDangXuatActionPerformed
//        URL iconURL = getClass().getResource("/image/ic_menu/ic_dangXuat.png");    
//        ImageIcon icon = new ImageIcon(iconURL);
        int result = JOptionPane.showConfirmDialog(
                    this,
                    "Bạn có chắc muốn đăng xuất?",
                    "Thông báo",
                    JOptionPane.YES_NO_OPTION
            );
            if (result == JOptionPane.YES_OPTION) {
                dispose();
                openLoginFrame();
            }
    }//GEN-LAST:event_BtnDangXuatActionPerformed

    private void btnKhachHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKhachHangActionPerformed
        if (switchToPanel("quanlyKHPanel", true)){
            quanlyKHPanel.load_KH();
            resetbgmenu();
            FocusableButtonmenu(btnKhachHang);
        };
    }//GEN-LAST:event_btnKhachHangActionPerformed

    private void btnThongKeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThongKeActionPerformed
        if (switchToPanel("thongKePanel", true)){
            thongKePanel.setupChart();
            resetbgmenu();
            FocusableButtonmenu(btnThongKe);
        };
    }//GEN-LAST:event_btnThongKeActionPerformed

    public void openLoginFrame (){
        javax.swing.SwingUtilities.invokeLater(() -> {
        LoginFrame FrameLogin = new LoginFrame(); 
        FrameLogin.setLocationRelativeTo(null); 
        FrameLogin.setVisible(true);   
        });
    };
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MemberFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MemberFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MemberFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MemberFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        //</editor-fold>

        //</editor-fold>

        //</editor-fold>

        //</editor-fold>

        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Avatar;
    private javax.swing.JPanel BorderLayout;
    private javax.swing.JButton BtnDangXuat;
    private javax.swing.JPanel JpanelMenu;
    private javax.swing.JButton btnBanHang;
    private javax.swing.JButton btnKhachHang;
    private javax.swing.JButton btnQlSanPham;
    private javax.swing.JButton btnThongKe;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanelInfo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel mainContentPanel;
    private javax.swing.JPanel menuPanel;
    private javax.swing.JLabel name;
    private javax.swing.JLabel position;
    // End of variables declaration//GEN-END:variables
}
